# frozen_string_literal: true

require "open3"
require "tempfile"

RSpec.describe JsxRosetta::Backend::RoutesScript do
  def emit(routes)
    described_class.new(source_path: "src/router.tsx", generated_at: "2026-05-09").emit(
      JsxRosetta::IR::RouteTree.new(routes: routes)
    )
  end

  it "produces a runnable Ruby script that lists parsed routes" do
    output = emit([
                    JsxRosetta::IR::RouteEntry.new(path: "/", element_name: "Home"),
                    JsxRosetta::IR::RouteEntry.new(path: "/posts/:id", element_name: "PostShow")
                  ])

    expect(output).to start_with("#!/usr/bin/env ruby\n")
    expect(output).to include("Generated by jsx_rosetta routes from src/router.tsx on 2026-05-09")
    expect(output).to include('{ path: "/", element: "Home" },')
    expect(output).to include('{ path: "/posts/:id", element: "PostShow" },')
  end

  it "emits commented-out `rails generate controller` calls" do
    output = emit([JsxRosetta::IR::RouteEntry.new(path: "/posts", element_name: "PostsIndex")])

    expect(output).to include('# system "rails", "generate", "controller", "posts_index", "index", "--skip-routes"')
  end

  it "infers `show` for path segments containing a parameter" do
    output = emit([JsxRosetta::IR::RouteEntry.new(path: "/posts/:id", element_name: "PostShow")])

    expect(output).to include('"show"')
  end

  it "emits a suggested config/routes.rb block" do
    output = emit([JsxRosetta::IR::RouteEntry.new(path: "/", element_name: "Home")])

    expect(output).to include("Rails.application.routes.draw do")
    expect(output).to include('get "/", to: "home#index"')
    expect(output).to include("end")
  end

  it "handles empty route trees" do
    output = emit([])

    expect(output).to include("No <Route> entries were recognized.")
  end

  it "produces syntactically valid Ruby" do
    routes = [
      JsxRosetta::IR::RouteEntry.new(path: "/", element_name: "Home"),
      JsxRosetta::IR::RouteEntry.new(path: "/posts/:id", element_name: "PostShow")
    ]
    output = emit(routes)

    Tempfile.create(["routes-script", ".rb"]) do |f|
      f.write(output)
      f.flush
      _, status = Open3.capture2e("ruby", "-c", f.path)
      expect(status).to be_success
    end
  end
end
