# frozen_string_literal: true

require_relative "../ast/inflector"

module JsxRosetta
  module Backend
    # Emits a reviewable Ruby script from an IR::RouteTree.
    #
    # The output prints the parsed routes, lists `system "rails", "generate",
    # "controller", ...` invocations (commented out by default), and a
    # suggested config/routes.rb block. The user is expected to review the
    # script, uncomment the commands they want to run, and execute it with
    # `ruby <output>.rb`.
    class RoutesScript
      def initialize(source_path: nil, generated_at: Time.now.utc.strftime("%Y-%m-%d"))
        @source_path = source_path
        @generated_at = generated_at
      end

      def emit(route_tree)
        lines = header_lines + body_lines(route_tree)
        "#{lines.join("\n")}\n"
      end

      private

      def header_lines
        provenance = @source_path ? "from #{@source_path}" : ""
        [
          "#!/usr/bin/env ruby",
          "# frozen_string_literal: true",
          "#",
          "# Generated by jsx_rosetta routes #{provenance} on #{@generated_at}.",
          "# Review this script. Uncomment the system() calls you want to run,",
          "# then execute with `ruby <this-file>`.",
          ""
        ]
      end

      def body_lines(route_tree)
        return ["puts 'No <Route> entries were recognized.'"] if route_tree.routes.empty?

        routes_array_lines(route_tree.routes) +
          [""] +
          report_lines +
          [""] +
          generator_lines(route_tree.routes) +
          [""] +
          routes_dsl_lines(route_tree.routes)
      end

      def routes_array_lines(routes)
        ["routes = ["] +
          routes.map { |r| "  { path: #{r.path.inspect}, element: #{r.element_name.inspect} }," } +
          ["]"]
      end

      def report_lines
        [
          %(puts "Parsed routes:"),
          %(routes.each { |r| puts "  \#{r[:path]} → \#{r[:element]}" })
        ]
      end

      def generator_lines(routes)
        ["# Run these by uncommenting the lines you want:"] + routes.map do |r|
          controller = AST::Inflector.underscore(r.element_name)
          action = action_for_path(r.path)
          %(# system "rails", "generate", "controller", "#{controller}", "#{action}", "--skip-routes")
        end
      end

      def routes_dsl_lines(routes)
        body = routes.map do |r|
          controller = AST::Inflector.underscore(r.element_name)
          action = action_for_path(r.path)
          "      get #{r.path.inspect}, to: \"#{controller}##{action}\""
        end
        [
          "puts <<~RB",
          "",
          "  # Suggested config/routes.rb additions:",
          "  Rails.application.routes.draw do"
        ] + body + [
          "  end",
          "RB"
        ]
      end

      def action_for_path(path)
        # Heuristic: paths that capture an `:id`-style segment look like a
        # show action; everything else defaults to index. The user can edit.
        path.match?(/:[a-zA-Z_]/) ? "show" : "index"
      end
    end
  end
end
